### ISSUE TITLE
建议做个浏览器插件，进入这些医院的网站给个警告

### ISSUE THREAD

**Issue by ToyYan** [langhua9527/Hospital#68]

**Comment by langhua9527** [comment]
你可以写一个，争取今天晚上更新可以用的JS数据文件

**Comment by LeonJavaAndroid** [comment]
已经有人做出来了
https://github.com/zhangjh/chromeExt/blob/master/%E8%8E%86%E7%94%B0%E7%B3%BB%E5%8C%BB%E9%99%A2%E6%A3%80%E6%B5%8B%E5%99%A8/README.md

**Comment by erichuang1994** [comment]
https://github.com/erichuang1994/PTXNotification
我也搞了一个

**Comment by t-k-** [comment]
如果题主有能力写的话也就不会在 issue 呼吁了。无非是希望 @langhua9527 借助这里的人气号召（比如写在readme）大家去写插件。
